"""
KirchhoffNet Synthetic Regression Training
==========================================
Two separate simulator calls per training step:

  .TRAN (per datapoint) -> V(output_node) at t=100ns  [forward-pass prediction]
  .OP   (once per epoch) -> dV(output_node)/dTheta_i   [adjoint sensitivity / gradient]

Why two calls:
  - TRAN captures the actual circuit dynamics from each IC input pattern
  - OP gives well-defined sensitivity at the DC operating point; with thetas < 1.7V
    all 4 PMOS loads are in the linear region so ALL 4 sensitivities are non-zero

Loss:
  L = (1/N) * sum_i (v_tran_i - target_i)^2

Gradient:
  dL/dtheta_j = (2/N) * sum_i (v_tran_i - target_i) * (dV_op / dtheta_j)

  The OP sensitivity is the same for all datapoints within an epoch (it depends
  only on current thetas, not on IC), so it is computed once and reused across
  all N datapoints in that epoch.

Dataset:
  10 datapoints with random IC voltages for all 4 ring nodes.
  Targets generated by running TRAN with teacher thetas [0.7, 0.7, 0.7, 0.7].
  Training starts from thetas [1.0, 1.0, 1.0, 1.0].
"""

import sys
import os
import json
import csv
import random

SIM_SRC = r"D:\Simulator\circuit_simulator-main\src"
if SIM_SRC not in sys.path:
    sys.path.insert(0, SIM_SRC)

from main import run_simulation_core
from netlist_generator import write_tran_netlist, write_op_netlist

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------
BASE_DIR     = r"D:\Kirchoffnet\kirchoff_claude"
NETLIST_DIR  = os.path.join(BASE_DIR, "temp_netlists")
LOG_FILE     = os.path.join(BASE_DIR, "training_log.csv")
DATASET_FILE = os.path.join(BASE_DIR, "dataset.json")

VDD          = 3.3
RING_NODES   = ["net2", "net3", "net4", "net6"]
THETA_PARAMS = ["V5", "V4", "V3", "V2"]

# Both teacher and training thetas must be < 1.7V for all sensitivities non-zero
TEACHER_THETAS = [0.5, 0.5, 0.5, 0.5]
TRAIN_THETAS   = [1.5, 1.5, 1.5, 1.5]

OUTPUT_NODE = "net2"
N_DATA = 10
LR     = 0.01
EPOCHS = 500
SEED   = 42


# ---------------------------------------------------------------------------
# Simulator calls
# ---------------------------------------------------------------------------

def get_tran_output(thetas, ic_dict, tag):
    """Run TRAN, return V(output_node) at final time step."""
    path = os.path.join(NETLIST_DIR, f"tran_{tag}.txt")
    write_tran_netlist(thetas, ic_dict, path)
    _, result = run_simulation_core(path, output_nodes=[OUTPUT_NODE])
    if result is None:
        raise RuntimeError(f"TRAN failed: thetas={thetas}, ic={ic_dict}")
    v_raw = result.get_voltage(OUTPUT_NODE)
    return float(v_raw[-1]) if hasattr(v_raw, "__len__") else float(v_raw)


def get_op_sensitivity(thetas, tag):
    """Run OP, return {param: dV(output_node)/dParam} for all 4 thetas."""
    path = os.path.join(NETLIST_DIR, f"op_{tag}.txt")
    write_op_netlist(thetas, path)
    _, result = run_simulation_core(path, output_nodes=[OUTPUT_NODE], sensitivity=True)
    if result is None:
        raise RuntimeError(f"OP failed: thetas={thetas}")
    available = result.get_sensitivity_parameters(OUTPUT_NODE) if result.sensitivities else []
    sens = {}
    for p in THETA_PARAMS:
        if p in available:
            raw = result.get_sensitivity(OUTPUT_NODE, p)
            sens[p] = float(raw[-1]) if hasattr(raw, "__len__") else float(raw)
        else:
            sens[p] = 0.0
    return sens


# ---------------------------------------------------------------------------
# Dataset generation
# ---------------------------------------------------------------------------

def generate_dataset():
    """Generate 10 datapoints using teacher thetas; save to dataset.json."""
    random.seed(SEED)
    print(f"Generating dataset with teacher_thetas={TEACHER_THETAS}")
    os.makedirs(NETLIST_DIR, exist_ok=True)

    dataset = []
    for i in range(N_DATA):
        ic = {n: round(random.uniform(0.0, VDD), 4) for n in RING_NODES}
        v_target = get_tran_output(TEACHER_THETAS, ic, tag=f"teacher_{i:02d}")
        dataset.append({"ic": ic, "target": v_target})
        print(f"  sample {i:2d}: ic={list(ic.values())}  target={v_target:.4f}V")

    with open(DATASET_FILE, "w") as f:
        json.dump(dataset, f, indent=2)
    print(f"Dataset saved -> {DATASET_FILE}\n")
    return dataset


def load_or_generate_dataset():
    if os.path.exists(DATASET_FILE):
        with open(DATASET_FILE) as f:
            dataset = json.load(f)
        print(f"Loaded dataset from {DATASET_FILE}  ({len(dataset)} samples)")
        return dataset
    return generate_dataset()


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train():
    os.makedirs(NETLIST_DIR, exist_ok=True)
    dataset = load_or_generate_dataset()
    N = len(dataset)

    thetas = list(TRAIN_THETAS)
    print(f"\nKirchhoffNet regression training  (TRAN output + OP sensitivity)")
    print(f"  Output node : {OUTPUT_NODE}")
    print(f"  N datapoints: {N}  |  Epochs: {EPOCHS}  |  LR: {LR}")
    print(f"  Init thetas : {thetas}  (teacher: {TEACHER_THETAS})")
    print(f"  Targets     : {[d['target'] for d in dataset]}")
    print("-" * 70)

    log_rows = [["epoch", "mse_loss"] + [f"theta{i+1}" for i in range(4)]
                + [f"sens_{p}" for p in THETA_PARAMS]]

    for epoch in range(1, EPOCHS + 1):

        total_sq_err = 0.0
        grad_num = [0.0] * 4
        last_sens = {}

        for i, sample in enumerate(dataset):
            # ── Per datapoint: run OP for sensitivity, TRAN for output ──
            sens   = get_op_sensitivity(thetas, tag=f"op_e{epoch:04d}_s{i:02d}")
            v_pred = get_tran_output(thetas, sample["ic"], tag=f"tran_e{epoch:04d}_s{i:02d}")

            error = v_pred - sample["target"]
            total_sq_err += error ** 2

            # Accumulate gradient: sum_i( error_i * dV_op/dtheta_j )
            for j, p in enumerate(THETA_PARAMS):
                grad_num[j] += error * sens[p]

            last_sens = sens  # keep last for logging

        # ── Batch update after all N datapoints ────────────────────────────
        # L        = (1/N) * sum_i(error_i^2)
        # dL/dθ_j  = (2/N) * sum_i( error_i * sens_j )
        mse = total_sq_err / N
        for j in range(4):
            thetas[j] -= LR * (2.0 / N) * grad_num[j]

        log_rows.append([epoch, mse] + list(thetas) + [last_sens.get(p, 0.0) for p in THETA_PARAMS])

        if epoch == 1 or epoch % 10 == 0:
            print(
                f"Epoch {epoch:4d}  MSE={mse:.6f}  "
                f"T=[{thetas[0]:.4f},{thetas[1]:.4f},{thetas[2]:.4f},{thetas[3]:.4f}]  "
                f"sens=[{last_sens.get('V5',0):+.3e},{last_sens.get('V4',0):+.3e},"
                f"{last_sens.get('V3',0):+.3e},{last_sens.get('V2',0):+.3e}]"
            )

    with open(LOG_FILE, "w", newline="") as f:
        csv.writer(f).writerows(log_rows)
    print(f"\nTraining complete. Log -> {LOG_FILE}")

    # Final evaluation
    print(f"\n--- Final evaluation (output_node={OUTPUT_NODE}) ---")
    print(f"{'#':>3}  {'target':>8}  {'v_tran':>8}  {'error':>8}  {'|error|':>8}")
    final_mse = 0.0
    for i, sample in enumerate(dataset):
        v_pred = get_tran_output(thetas, sample["ic"], tag=f"final_{i:02d}")
        err = v_pred - sample["target"]
        final_mse += err ** 2
        print(f"{i:3d}  {sample['target']:8.4f}  {v_pred:8.4f}  {err:+8.4f}  {abs(err):8.4f}")

    final_mse /= N
    print(f"\nFinal MSE : {final_mse:.6f}")
    print(f"Final thetas: {thetas}")
    return thetas


if __name__ == "__main__":
    final_thetas = train()
    print(f"\nDone. Final thetas: {final_thetas}")
